-- MySQL Script generated by MySQL Workbench
-- Wed Dec  1 18:24:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarritodeCompras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarritodeCompras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarritodeCompras` DEFAULT CHARACTER SET utf8 ;
USE `CarritodeCompras` ;

-- -----------------------------------------------------
-- Table `CarritodeCompras`.`Musuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`Musuario` (
  `id_usu` INT NOT NULL AUTO_INCREMENT,
  `nom_usu` VARCHAR(20) NOT NULL,
  `appat_usu` VARCHAR(20) NOT NULL,
  `apmat_usu` VARCHAR(20) NOT NULL,
  `fecnac_usu` VARCHAR(20) NOT NULL,
  `tel_usu` BIGINT(10) NOT NULL,
  `cel_usu` BIGINT(10) NOT NULL,
  `email_usu` VARCHAR(30) NOT NULL,
  `pass_usu` VARCHAR(30) NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`id_usu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`TipoTarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`TipoTarjeta` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`mtarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`mtarjeta` (
  `id_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `num_tarjeta` BIGINT(16) NOT NULL,
  `fecha_exp` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `id_usu` INT NOT NULL,
  INDEX `id_tipo_idx` (`id_tipo` ASC) VISIBLE,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `fk_mtarjeta_Musuario1_idx` (`id_usu` ASC) VISIBLE,
  CONSTRAINT `id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `CarritodeCompras`.`TipoTarjeta` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usutarjeta`
    FOREIGN KEY (`id_usu`)
    REFERENCES `CarritodeCompras`.`Musuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`CFormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`CFormaPago` (
  `id_forma` INT NOT NULL AUTO_INCREMENT,
  `forma_pago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_forma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`MCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`MCompra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `fecha_compra` VARCHAR(45) NOT NULL,
  `total_compra` DOUBLE NOT NULL,
  `id_forma` INT NOT NULL,
  `id_usu` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `id_forma_idx` (`id_forma` ASC) VISIBLE,
  INDEX `fk_MCompra_Musuario1_idx` (`id_usu` ASC) VISIBLE,
  CONSTRAINT `id_forma`
    FOREIGN KEY (`id_forma`)
    REFERENCES `CarritodeCompras`.`CFormaPago` (`id_forma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usu`
    FOREIGN KEY (`id_usu`)
    REFERENCES `CarritodeCompras`.`Musuario` (`id_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`CSabor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`CSabor` (
  `id_sabor` INT NOT NULL AUTO_INCREMENT,
  `tipo_sabor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_sabor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`CDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`CDescuento` (
  `id_descuento` INT NOT NULL AUTO_INCREMENT,
  `porcentaje` INT NOT NULL,
  PRIMARY KEY (`id_descuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`CPresentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`CPresentacion` (
  `id_presentacion` INT NOT NULL AUTO_INCREMENT,
  `tipo_presentacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_presentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`CTamano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`CTamano` (
  `id_tamano` INT NOT NULL AUTO_INCREMENT,
  `tipo_tamano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tamano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`MProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`MProducto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `id_sabor` INT NOT NULL,
  `id_tamano` INT NOT NULL,
  `id_descuento` INT NOT NULL,
  `id_presentacion` INT NOT NULL,
  `cantidad_unidades` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_sabor_idx` (`id_sabor` ASC) VISIBLE,
  INDEX `id_descuento_idx` (`id_descuento` ASC) VISIBLE,
  INDEX `id_presentacion_idx` (`id_presentacion` ASC) VISIBLE,
  INDEX `id_tamano_idx` (`id_tamano` ASC) VISIBLE,
  CONSTRAINT `id_sabor`
    FOREIGN KEY (`id_sabor`)
    REFERENCES `CarritodeCompras`.`CSabor` (`id_sabor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_descuento`
    FOREIGN KEY (`id_descuento`)
    REFERENCES `CarritodeCompras`.`CDescuento` (`id_descuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_presentacion`
    FOREIGN KEY (`id_presentacion`)
    REFERENCES `CarritodeCompras`.`CPresentacion` (`id_presentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tamano`
    FOREIGN KEY (`id_tamano`)
    REFERENCES `CarritodeCompras`.`CTamano` (`id_tamano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarritodeCompras`.`DCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarritodeCompras`.`DCompra` (
  `id_dcompra` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `cantidad_dcompra` INT NOT NULL,
  `subtotal_dcompra` DOUBLE NOT NULL,
  `id_compra` INT NOT NULL,
  PRIMARY KEY (`id_dcompra`),
  INDEX `id_compra_idx1` (`id_compra` ASC) VISIBLE,
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `id_compra`
    FOREIGN KEY (`id_compra`)
    REFERENCES `CarritodeCompras`.`MCompra` (`id_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `CarritodeCompras`.`MProducto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
